name: build_package
on:
  workflow_call:
    inputs:
      solutionFile:
        required: true
        type: string
      nugetDirecory:
        required: true
        type: string

jobs:
  build:
    name: Build Package
    runs-on: windows-2022
    environment: Testing

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore NuGet Packages
        run: nuget restore ${{ inputs.solutionFile }}

      - name: Build Project
        run: msbuild ${{ inputs.solutionFile }} /p:Configuration=Release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: nuget
          if-no-files-found: error
          path: ${{ inputs.nugetDirecory }}/*nupkg
