name: check_version
on:
  workflow_call:
    inputs:
      projectFile:
        required: true
        type: string

jobs:
  check_version:
    name: Check Version Number
    runs-on: ubuntu-latest
    environment: Testing

    steps:
      - name: Checkout current commit
        uses: actions/checkout@v4
        with:
          path: current
          sparse-checkout: ${{ inputs.projectFile }}

      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: 'main'
          path: main
          sparse-checkout: ${{ inputs.projectFile }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install semver
        run: python -m pip install semver
    
      - name: Check version numbers
        shell: bash
        run: |
          version_current=$(grep '<Version>' "./current/${{ inputs.projectFile }}" | sed "s|^[ ]*||;s|<Version>||;s|</Version>||")
          version_main=$(grep '<Version>' "./main/${{ inputs.projectFile }}" | sed "s|^[ ]*||;s|<Version>||;s|</Version>||")

          if [ ! $(python -c "import semver; print(semver.compare(\"$version_current\", \"$version_main\"))") == 1 ]; then
            echo "::error title=Invalid version number::Version number must be increased on pushes to main"
            exit 1
          fi