name: test_build
on:
  pull_request:
    branches:
      - 'main'

jobs:
  check_version:
    uses: ./.github/workflows/check_version.yml
    with:
      projectFile: OpenEphys.Sockets.Bonsai/OpenEphys.Sockets.Bonsai/OpenEphys.Sockets.Bonsai.csproj
  
  build:
    uses: ./.github/workflows/build_package.yml
    needs: check_version
    with:
      solutionFile: ./OpenEphys.Sockets.Bonsai/OpenEphys.Sockets.Bonsai.sln
      nugetDirecory: ./OpenEphys.Sockets.Bonsai/bin/Release
